cc_library(
    name = "gates",
    srcs = [
        "nand.cpp", 
        "signal.cpp", 
        "half_adder.cpp", 
        "or.cpp", 
        "adder.cpp", 
        "bitwise_adder.cpp", 
        "decoder.cpp",
        "register.cpp",
        "data.cpp",
        "rom.cpp",
        "ram.cpp"
    ],
    hdrs = [
        "gate.hpp", 
        "nand.hpp", 
        "signal.hpp", 
        "half_adder.hpp", 
        "or.hpp", 
        "adder.hpp", 
        "bitwise_adder.hpp", 
        "decoder.hpp",
        "register.hpp",
        "data.hpp",
        "rom.hpp",
        "ram.hpp"
    ],
    visibility = ["//main:__pkg__"]
)