version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: empty
      POSTGRES_DB: secrets
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped


  api:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres

volumes:
  postgres: